baseURL = "https://blog.kiwiyou.dev/"
languageCode = "ko-kr"
title = "키위밭"
theme = "PaperMod"
googleAnalytics = 'G-HR57EWWSWP'

enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[minify]
minifyOutput = false

[params]
title = "키위밭"
description = "kiwiyou의 Rust 개발 블로그"
keywords = ["Rust", "PS", "Algorithm", "kiwiyou"]
author = "kiwiyou"
socialIcons = [
    { name = "twitter", url = "https://twitter.com/giwiyou" },
    { name = "github", url = "https://github.com/kiwiyou" },
]
dateFormat = "2006년 1월 2일"

[params.profileMode]
enabled = true
title = "kiwiyou"
subtitle = "Rust를 좋아하는 프로그래머입니다."
imageUrl = "psa.jpg"
imageTitle = "kiwi"

[params.assets]
disableHLJS = true

[menu]
main = [
    { name = "PS", url = "ps" },
    { name = "검색", url = "search" },
]

[markup.goldmark.renderer]
unsafe = true
